packages:
  - services/*
  - services/*/app
  - services/*/functions
  - packages/*

catalog:
  '@aws-sdk/client-dynamodb': 3.632.0
  '@aws-sdk/client-kms': 3.632.0
  '@aws-sdk/client-ses': 3.632.0
  '@aws-sdk/lib-dynamodb': 3.632.0
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.1
  '@testing-library/user-event': ^14.6.1
  '@types/aws-lambda': ^8.10.159
  '@types/node': ^22
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitest/browser-playwright': ^4.0.16
  '@vitest/coverage-v8': ^4.0.16
  aws-cdk-lib: 2.201.0
  constructs: 10.3.0
  eslint: ^9.39.2
  playwright: ^1.57.0
  react: ^19.2.3
  react-dom: ^19.2.3
  react-icons: ^5.5.0
  sst: 2.49.6
  tsup: ^8.3.5
  typescript: ^5.9.3
  vite: ^7.1.7
  vitest: 4.0.16
  zod: ^4.2.1

overrides:
  aws-cdk-lib: 2.233.0
