packages:
  - 'services/*'
  - 'packages/*'

catalog:
  react: ^19.2.3
  react-dom: ^19.2.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  typescript: ^5.9.3
  zod: ^4.2.1
  vitest: ^4.0.16
  '@vitest/coverage-v8': ^4.0.16
  '@testing-library/react': ^16.3.1
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/user-event': ^14.6.1
